#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Mar 19 17:10:08 2022

@author: guo.1648
"""

# based on the cGAN_to_orig_cls_map_final.pkl generated in find_orgCls_chenqi_step2.py,
# rename the sub-class folders generated by cGAN.

import os
import pickle
import shutil


rootDir = '/eecf/cbcsl/data100b/Chenqi/transitional-cGAN/results/generate/'

srcFolder = 'Amphibians_128-009200/a/'
dstFolder = 'rename/'

pklFullName = '/eecf/cbcsl/data100b/Chenqi/transitional-cGAN/datasets/Amphibians_128_map/cGAN_to_orig_cls_map_final.pkl'


def get_clsFolders(this_dir):
    for (dirpath, dirnames, filenames) in os.walk(this_dir):
        return dirnames



if __name__ == '__main__':
    f_pkl = open(pklFullName,'rb')
    cGAN_to_orig_cls_map_final = pickle.load(f_pkl)
    f_pkl.close()
    
    for cGAN_cls in cGAN_to_orig_cls_map_final:
        orig_cls = cGAN_to_orig_cls_map_final[cGAN_cls]
        
        this_srcFolderFullDir = rootDir + srcFolder + str(cGAN_cls) + '/'
        assert(os.path.exists(this_srcFolderFullDir))
        
        this_dstFolderFullDir = rootDir + dstFolder + str(orig_cls) + '/'
        if not (os.path.exists(this_dstFolderFullDir)):
            os.mkdir(this_dstFolderFullDir)
        
        for (dirpath, dirnames, filenames) in os.walk(this_srcFolderFullDir):
            for filename in filenames:
                if ".jpg" in filename or ".png" in filename:
                    print("------------------deal with---------------------")
                    print(filename)
                    
                    srcImg = this_srcFolderFullDir + filename
                    dstImg = this_dstFolderFullDir + filename
                    
                    shutil.move(srcImg, dstImg)
                    
                    #print()
                    
                    
    
    


