#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep 30 18:43:22 2022

@author: guo.1648
"""


# extract the images generated by my_sample.sh (saved in npz file),
# and save as png image files.


import numpy as np
from PIL import Image


rootDir = '/eecf/cbcsl/data100b/Chenqi/guided-diffusion/results/classifier_diffusion/Amphibians/sampling_resumed/b/'

srcFile = 'samples_10000x128x128x3.npz'
dstFolder = 'imgs/'


content = np.load(rootDir+srcFile)

imgs_arr = content['arr_0']
labels = content['arr_1']


for i in range(10000): # num of images
    this_img_arr = imgs_arr[i,:,:,:]
    #print()
    im = Image.fromarray(this_img_arr)
    im.save(rootDir + dstFolder + str(i) + ".png")


